import { Struct, size } from 'superstruct';

export const Defaults = {
  Task: {
    id: '',
    title: '',
    status: 'OPEN',
    priority: '',
    project: '',
    scope: '',
    description: '',
    notes: '',
    definitionOfDone: '',
    prompt: '',
    results: {},
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subtasks: [],
  },
  SoterIncident: {
    id: '',
    request: '',
    riskScore: 0,
    resolved: false,
    timestamp: new Date().toISOString(),
    patterns: [],
    response: '',
  },
  SoterReview: {
    id: '',
    incidentId: '',
    status: '',
    priority: '',
    decision: '',
    createdAt: new Date().toISOString(),
  },
  EpistemicMark: {
    id: '',
    label: 'UNCERTAIN',
    topic: '',
    reasoningChain: '',
    sessionId: '',
    timestamp: new Date().toISOString(),
  },
  ShadowEntry: {
    id: '',
    category: '',
    content: '',
    sessionId: '',
    timestamp: new Date().toISOString(),
  },
  SymbolNode: {
    id: '',
    name: '',
    stage: 'NIGREDO',
    intention: '',
  },
  BenchmarkResult: {
    id: '',
    queryId: 0,
    category: '',
    queryText: '',
    normalResponse: '',
    abraxasResponse: '',
    scores: {
      nl: { known: 0, inferred: 0, uncertain: 0, unknown: 0, dream: 0 },
      al: { known: 0, inferred: 0, uncertain: 0, unknown: 0, dream: 0 },
    },
    modelId: '',
    timestamp: new Date().toISOString(),
  },
  MemoryFragment: {
    id: '',
    fragment: '',
    provenance: '',
    timestamp: new Date().toISOString(),
  },
  Concept: {
    id: '',
    name: '',
    description: '',
  },
  ActionablePlan: {
    id: '',
    summary: '',
    steps: [],
    riskAssessment: '',
    groundingStatus: 'UNKNOWN',
  },
  JanusConsensus: {
    id: '',
    claim: '',
    evidence: [],
    confidence: 0.0,
    label: 'UNCERTAIN',
    timestamp: new Date().toISOString(),
  },
  QualiaBridge: {
    id: '',
    solSide: '',
    noxSide: '',
    bridgeStatus: '',
    resonance: 0.0,
  },
  EdgeInfo: {
    id: '',
    from: '',
    to: '',
    createdAt: new Date().toISOString(),
  },
};

export type DefaultType = keyof typeof Defaults;
